language: scala

scala:
  - 2.13.10

jdk: openjdk20

# Use container-based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete

script:
  - sbt -J--add-opens=java.base/sun.security.ssl=ALL-UNNAMED clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
